name: Publish GitHub Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - .github/
      - .maven/
      - README.md
      - .gitignore
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build artifact
        run: mvn package --batch-mode
      - name: Deploy package to GitHub maven
        run: mvn deploy:deploy-file@github-deploy --batch-mode -s .maven/settings.xml
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USERNAME: mulesoft-consulting
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mule-artifact
          path: main/target/*.jar
