name: Publish GitHub Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - .github/
      - .maven/
      - README.md
      - .gitignore
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Deploy package to GitHub maven
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mule-artifact
          path: target/*.jar
